feat: 유저의 거래 횟수 반환 API
bunderLikeLion/sellon_backend pull request #151
Opened 2022-08-10 01:31 UTC by yuujinkim

## 작업 내용
- GET: /users/user/:id/dealings_count/
- dealing에서 product.user, product_group.user를 이용해서 가져오기

## 참고 자료
- webapp/dealing/views/count_completed_api_view.py

## 희망 완료일
- ASAP

2022-08-10 12:58 UTC, shinkeonkim commented on webapp/user/views.py
> +        product_group_count = Dealing.objects.filter(product_group__user=request.user).count()
pk로 넘어온 user id를 이용해서 user값을 가져와주세요.

user = get_object_or_404(pk=user)
 product_count = Dealing.objects.filter(product__user=user).count()

2022-08-10 12:58 UTC, shinkeonkim requested changes
코멘트 확인바람요

2022-08-10 14:28 UTC, yuujinkim commented on webapp/user/views.py
> +        product_group_count = Dealing.objects.filter(product_group__user=request.user).count()
반영했습니다

2022-08-10 17:05 UTC, shinkeonkim approved these changes
LGTM

2022-08-11 08:37 UTC, songks0922 approved these changes
LGTM

2022-08-11 10:37 UTC, shinkeonkim commented
main이랑 충돌나는 부분 제가 잡았어요

2022-08-11 10:37 UTC, merged