Rating api
bunderLikeLion/sellon_backend pull request #161
Opened 2022-08-12 09:46 UTC by yuujinkim

## 작업 내용
- 유저마다 평점 API (GET: /users/user/:id/rating)

## 참고 자료

## 희망 완료일
- ASAP

2022-08-12 13:20 UTC, shinkeonkim requested changes

2022-08-12 13:20 UTC, shinkeonkim commented on webapp/user/views/user_view.py
> +            return Response({'rating': qs})
p1: 평균구하는 내용은 어디있나요?

2022-08-15 04:00 UTC, yuujinkim commented on webapp/user/views/user_view.py
> +            return Response({'rating': qs})
수정했습니다.

2022-08-15 04:23 UTC, shinkeonkim requested changes

2022-08-15 04:23 UTC, shinkeonkim commented on webapp/user/views/user_view.py
> +            return Response({'rating': 0})
p1: error exception을 잡는게 아니라 count가 0보다 큰 걸로 분기를 거는게 어때요?

2022-08-15 04:29 UTC, shinkeonkim commented on webapp/user/views/user_view.py
> +            return Response({'rating': 0})
result = result / count if count> 0 else 0

2022-08-15 06:18 UTC, yuujinkim commented on webapp/user/views/user_view.py
> +            return Response({'rating': 0})
반영했습니다.

2022-08-15 08:12 UTC, merged