feat: admin 에서 completed-dealings-count 초기화 할 수 있는 액션 생성
bunderLikeLion/sellon_backend pull request #193
Opened 2022-08-18 17:08 UTC by koomchang

## 작업 내용
- feat: admin 에서 completed-dealings-count 초기화 할 수 있는 액션 생성

## 참고 자료
- 

## 희망 완료일
- ASAP

2022-08-18 23:33 UTC, shinkeonkim requested changes

2022-08-18 23:33 UTC, shinkeonkim commented on webapp/user/admin.py
> +        user.completed_dealings_count = 0
0으로 초기화하는게 아니라 완료된 거래 횟수를 넣어달라는 요구사항이에요ㅠㅠ

2022-08-19 02:13 UTC, koomchang commented on webapp/user/admin.py
> +        user.completed_dealings_count = 0
앗 오키 초기화해달라는 건줄 알았어

2022-08-19 06:54 UTC, shinkeonkim approved these changes

2022-08-19 06:54 UTC, merged