feat : pagination 구현
bunderLikeLion/sellon_backend pull request #22
Opened 2022-07-20 16:10 UTC by koomchang

## 작업 내용
- pagination class 구현

## 참고 자료
- django 공식문서 - paginator 
- https://docs.djangoproject.com/en/4.0/ref/paginator/#django.core.paginator.Paginator
- django rest framework 공식문서 PageNumberPagination 
- https://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination

## 희망 완료일
- 07/23

2022-07-20 16:22 UTC, koomchang commented on .vscode/settings.json
> +}
q : 이거 gitignore 에 들어가야 하지 않나요?

2022-07-21 14:23 UTC, shinkeonkim commented on .vscode/settings.json
> +}
이거는 들어가있는게 좋을 것 같아요

2022-07-21 14:24 UTC, shinkeonkim commented on .vscode/settings.json
> +}
근데 이 내용이 왜 이 PR에 포함되었을까요..?

2022-07-21 14:28 UTC, shinkeonkim requested changes

2022-07-21 14:28 UTC, shinkeonkim commented on webapp/config/settings/base.py
> +    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination'
```suggestion
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.PageNumberPagination'
```
p1: 위와 같이 되어야하지 않을까요?

2022-07-21 14:28 UTC, shinkeonkim commented on webapp/config/pagination.py
> +    # 임시 설정
```suggestion
    page_size = 10
```
p2: 10개정도가 무난할 것 같슴다

2022-07-21 14:28 UTC, shinkeonkim commented on webapp/config/pagination.py
> +        return Response(OrderedDict([
q: OrderedDict를 써야하는 이유가 있나요?

2022-07-21 14:28 UTC, shinkeonkim commented on webapp/config/pagination.py
> +        return Response(OrderedDict([
p2: 바로 dictionary를 넣어도 될 것 같은데요

2022-07-22 00:00 UTC, koomchang commented on .vscode/settings.json
> +}
pull 하고 push 하니깐 따라 온거 같더라구

2022-07-22 00:10 UTC, koomchang commented on webapp/config/settings/base.py
> +    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination'
수정했습니다.

2022-07-22 00:11 UTC, koomchang commented on webapp/config/pagination.py
> +        return Response(OrderedDict([
수정했습니다.

2022-07-22 15:10 UTC, shinkeonkim commented
![image](https://user-images.githubusercontent.com/47373998/180469208-d6474088-9e97-4fe4-9e9a-c64a64ba778e.png)
@koomchang 작업을 완료하시구나서, 재리뷰 요청은 이미지에 표시한 걸 클릭하시면 됩니당

2022-07-23 14:20 UTC, koomchang commented
> ![image](https://user-images.githubusercontent.com/47373998/180469208-d6474088-9e97-4fe4-9e9a-c64a64ba778e.png) @koomchang 작업을 완료하시구나서, 재리뷰 요청은 이미지에 표시한 걸 클릭하시면 됩니당

넵

2022-07-24 08:40 UTC, shinkeonkim approved these changes
고생하셨습니다 :)

2022-07-25 15:14 UTC, yuujinkim approved these changes

2022-07-25 15:15 UTC, merged