item-model
bunderLikeLion/sellon_backend pull request #28
Opened 2022-07-27 14:52 UTC by songks0922

## 작업 내용
- Product, Inventroy 모델 추가 및 Config에 BaseModel 작성
- migrate

2022-07-27 16:43 UTC, koomchang commented on webapp/product/models.py
> +        verbose_name='수량',
p2 : quality 는 품질, quantity 가 수량입니다

2022-07-28 06:00 UTC, songks0922 commented on webapp/product/models.py
> +        verbose_name='수량',
quantity로 수정하겠습니다

2022-07-28 11:11 UTC, shinkeonkim commented on webapp/config/models.py
> +        abstract = True
https://github.com/shinkeonkim/django-coffee-model

2022-07-28 11:57 UTC, songks0922 commented on webapp/config/models.py
> +        abstract = True
수정했습니다

2022-07-29 05:13 UTC, koomchang submitted a review, later dismissed
LGTM

2022-07-29 10:10 UTC, shinkeonkim commented on webapp/product/models.py
> +        verbose_name='수량',
???? quality가 맞아요

2022-07-29 10:10 UTC, shinkeonkim commented on webapp/product/models.py
> +        verbose_name='수량',
해당 모델에서 수량을 의도한게 아니라 품질을 의도한 거였어요

2022-07-29 10:13 UTC, shinkeonkim commented on webapp/product/models.py
> +        verbose_name='수량',
그리고 품질도 Enum으로 관리해야 할 것 같습니다.

2022-07-29 10:14 UTC, shinkeonkim commented on webapp/product/models.py
> +        verbose_name='수량',
ex. https://www.b-list.org/weblog/2007/nov/02/handle-choices-right-way/

```
class Entry(models.Model):
    LIVE_STATUS = 1
    DRAFT_STATUS = 2
    HIDDEN_STATUS = 3
    STATUS_CHOICES = (
        (LIVE_STATUS, 'Live'),
        (DRAFT_STATUS, 'Draft'),
        (HIDDEN_STATUS, 'Hidden'),
    )
    # ...some other fields here...
    status = models.IntegerField(choices=STATUS_CHOICES, default=LIVE_STATUS)

```

2022-07-29 10:17 UTC, shinkeonkim requested changes

2022-07-29 10:17 UTC, shinkeonkim commented on webapp/config/models.py
> +class BaseModelWithDeleted(BaseModel):
```suggestion
class SoftDeleteBaseModel(BaseModel):
```
은 어때요?

2022-07-29 10:17 UTC, shinkeonkim commented on webapp/config/models.py
> +    objects = DeletedModelManager()
```suggestion
    objects = SoftDeleteBaseModelManager()
```
위 리뷰대로 하면, 모델명 뒤에 Manager를 붙여서 일관성있게 해주세욥

2022-07-29 10:17 UTC, shinkeonkim commented on webapp/product/admin.py
> +# from django.contrib import admin
comment: 어드민은 다음 이슈로 만들어두겠습니다.

2022-07-29 10:35 UTC, shinkeonkim commented on webapp/product/models.py
> +        verbose_name='수량',
quantity도 필요하다고 하니, 둘다 넣읍시다

2022-07-29 11:51 UTC, shinkeonkim approved these changes

2022-07-30 04:53 UTC, koomchang approved these changes

2022-07-30 04:58 UTC, merged