fix: product quality choices lang to eng
bunderLikeLion/sellon_backend pull request #76
Opened 2022-07-31 17:41 UTC by koomchang

## 작업 내용
- fix: product quality choices lang to eng

## 참고 자료
- 

## 희망 완료일
- ASAP

2022-07-31 18:28 UTC, songks0922 submitted a review, later dismissed
LGTM

2022-08-01 01:08 UTC, shinkeonkim commented on webapp/product/models/product.py
> +        (5, 'excellent'),
```suggestion
        (1, 'very_poor'),
        (2, 'poor'),
        (3, 'good'),
        (4, 'very_good'),
        (5, 'excellent'),

```

p1: 공백문자가 enum 값에 들어가는건 지양합니다

2022-08-01 01:08 UTC, shinkeonkim requested changes
리뷰 확인해주세욥

2022-08-01 04:16 UTC, koomchang commented on webapp/product/models/product.py
> +        (5, 'excellent'),
수정했습니다.

2022-08-01 08:03 UTC, songks0922 approved these changes

2022-08-01 08:16 UTC, shinkeonkim reviewed
마이그레이션 한번 돌려주세요!

2022-08-01 08:20 UTC, koomchang commented
> Member

수정했습니다.

2022-08-01 08:57 UTC, shinkeonkim approved these changes

2022-08-01 09:15 UTC, merged