feat: message crud api 연결
bunderLikeLion/sellon_backend pull request #80
Opened 2022-08-01 09:25 UTC by koomchang

## 작업 내용
- feat: message crud api 연결

## 참고 자료
- 

## 희망 완료일
- ASAP

2022-08-01 09:58 UTC, shinkeonkim requested changes

2022-08-01 09:58 UTC, shinkeonkim commented on webapp/message/views.py
> +
p1: List, Show에서 request.user가 보냈거나 받은 메세지만 나와야 함.

2022-08-01 09:58 UTC, shinkeonkim commented on webapp/message/serializers/message_serializer.py
> +        ]
p1: sender, receiver는 UserAbstractSerializer를 read_only로 쓰고,
receiver_id를 write_only로 하나 PrimaryKeyRealtedField로 해야할 것 같습니다.

2022-08-01 09:58 UTC, shinkeonkim commented on webapp/message/views.py
> +
p1: 어떤 유저와 메세지를 나누었는지를 filtering 할 수 있어야 함.

2022-08-01 09:58 UTC, shinkeonkim commented on webapp/message/views.py
> +
p1: created_at 기준으로 정렬 가능해야 함.

2022-08-01 09:58 UTC, shinkeonkim commented on webapp/message/permissions.py
> +        return request.user and (request.user == obj.sender or request.user.is_staff)
p1: 여기서는 request.user.is_staff 이거 없어도 될 것 같습니다. 메세지를 어드민이 조작하는건 이상해요

2022-08-01 09:58 UTC, shinkeonkim commented on webapp/message/permissions.py
> +        return request.user and (request.user == obj.sender or request.user.is_staff)
```suggestion
        return request.user and request.user == obj.sender
```

2022-08-03 05:54 UTC, songks0922 approved these changes
LGTM

2022-08-03 05:54 UTC, songks0922 commented on webapp/message/permissions.py
> +        return request.user and (request.user == obj.sender or request.user.is_staff)
이거 반영 된거 맞죠?

2022-08-04 13:43 UTC, yuujinkim approved these changes
LGTM

2022-08-05 15:09 UTC, shinkeonkim commented
기획이 변경되어서 close 해두겠습니다

2022-08-05 15:09 UTC, closed without merging